version: '3.3'

services:
  mongodb:
    image: mongo:5.0.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./backend/data:/data/db
    ports:
      - 27017:27017

  kibby-user:
    build: ./backend/services/user
    restart: always
    environment:
      - MONGO_URI=mongodb://root:root@localhost:27017
    ports:
      - 5100:5000

volumes:
  data: {}
